### ISSUE TITLE
RFC:  Version 1 Release

### ISSUE THREAD

**Issue by wshafer** [reliv/rwriter#15]
Hey Guys,

I'd like to open up a conversation about where we are for a 1.0 release and the things that we'd still like to complete/fix.  This way we can setup some milestones and have something to work towards.

To start this off some things I think we still need before we launch

* Migrate to ZF 3 due out at the end of the month.  Docs are already in place to show what needs to be migrated over.  The big pluses are performance increases for the Service Manager and Module Managers.
* A completed theme with all the needed css for the "core" plugins
* Define a list of core plugins for this release
* Remove the event handlers (where possible).  This is a BC break but I'd like to see the event handlers all go away.  For instance, now that the CMS has a dedicated route, we can remove the redirect to 404 and the not authorized redirect to the ZF error handler.
* Make the CMS layout override optional
* Add Icons for "core" plugins
* Get the Admin menu responsive (add bootstrap css to menu)
* Add a new menu to the containers to add a new plugin to the container without drag/drop.
* Launch a R-Writer website.
* Document theme building and plugin writing.

**Comment by rodmcnew** [comment]
I question migrating to ZF3 rather than SF2. All we are really using in ZF are the router, service manager, config, and module manager. After playing with the Drupal 8 RC, I've found that all four of these ZF parts are inferior to their SF counterparts.

ZF's service manager is so bad compared to SF that we had to write our own
ZF's routing configs are so bad that after years, still no one on our team knows how to write one by hand
ZF's module manger's way of combining all the config of a module into a single file makes finding route and services annoying and very scrolly
SF has much higher adoption and communit.

**Comment by wshafer** [comment]
A move to SF2 is way more invasive.  We are using a lot more then the services noted.  We are also using the MVC stack, Form, and input filters.

Seems the only thing that wouldn't be touched moving to SF 2 is the Models.  All the controllers and views would have to be changed.  All the internal logic in the CMS would be need to change.  All the factories changed.  Seems we'd be starting over.  In your world that's a lot more then the CMS.

Something tells me that a switch to SF 2 would take months to years to complete, vs a month or two to move to ZF 3.

**Comment by rodmcnew** [comment]
Hmm... At Reliv we are experimenting with the idea of writing any new functionality as Symfony bundles rather than ZF modules. We believe this may be the best thing for us as developers and for the company in the long term. 

We have a library that allows Symfony bundles to run in ZF2 (https://github.com/reliv/symfonize-zf/tree/0.3.1).

This isn't for sure yet but we have been playing with this idea. If this happens, we may be looking to add a Symfony-bundle based plugin interface for RCM eventually. There are thoughts that RCM could slowly become more framework agnostic and decoupled from the framework layer.

**Comment by jerv13** [comment]
Of course I agree with being more framework agnostic and decoupled.  It will take time to get things working in that way.

**Comment by wshafer** [comment]
I've been doing a lot of research lately and I thing we all may be a bit dated.  Both ZF3 and Symphony 3 are moving to middleware PSR 7.  Maybe the best approach is to try and get "core" to act as a middleware layer using PSR7 and the new container-interop (https://github.com/container-interop/container-interop) for managing services.  In addition we should move the API pieces out of core and into it's own module.

At that point the framework becomes irrelivant.

**Comment by wshafer** [comment]
With that said, we're still talking about months of delay.  Perhaps we make shifting frameworks (or removing that dependency) to  a 2.0 release?.  We know the CMS in it's current form is stable and working well, I'd like to push to get a official release out the door, once that happens the skys the limit.  Thoughts?

**Comment by rodmcnew** [comment]
- - PSR7 - - 
I completely agree that the PSR7 request and response pattern should be used. We could consider having a plugin interface built around this pattern. The biggest change here would be getting the RCM to stop speaking ZF view models everywhere.

I would like to see both plugins and apps be able to return PSR7 responses in RCM. Just these two changes would eliminate all barriers from RCM to Reliv writing future code as Symfony bundles. @jerv13  agrees with this.

 - - Framework Independence - -
We have been playing around with the idea of putting any classes that do not reference a framework in a separate package as a starting step. This would allow us to clearly see what code is framework dependent, and what code is more like a class library. We've tried this with some internal modules and it seems to have worked well. As @wshafer pointed out, the http API parts will always be framework dependent so they should move out.

- - 1.0 - - 
@jerv13 Seems to question our readiness for a 1.0 release. My question for @wshafer is this: What exactly do we really need to do 1.0-ize? Are we talking about tagging every package or just the skel app?

**Comment by rodmcnew** [comment]
@jerv13 I have no issue with just calling what we have now 1.0. What are your aversions to this?

**Comment by jerv13** [comment]
I have no aversions to releasing a ZF2 v1.0 AS IS, we might tackle a couple of the bullets:

nope - Migrate to ZF 3 due out at the end of the month.
yes   - A completed theme with all the needed css for the "core" plugins
yes   - Define a list of core plugins for this release
2.0    - Remove the event handlers (where possible). 
2.0    - Make the CMS layout override optional
yes   - Add Icons for "core" plugins
maybe - Get the Admin menu responsive (add bootstrap css to menu)
nope    - Add a new menu to the containers to add a new plugin to the container without drag/drop.
nope    - Launch a R-Writer website.
limited  - Document theme building and plugin writing.

Part of our road-map for 2.0 needs to be:
- Decoupling from frameworks
- Utilizing PSR7 and generic PHP interfaces
- Remove ZF event handlers

The most important thing right now is too have a clear road-map for the future that is documented.
We will not have a lot of company time to devote to a real "release".  I am willing to put in a couple personal hours in to get a bit of traction going.

For example, I can put together some icons in my spare time.

**Comment by jerv13** [comment]
I addition, may plugins need to be split out from our junk drawer and the bower bits need to be addressed.

**Comment by jerv13** [comment]
@wshafer I will deprecate the RCM API classes.  We are using the Api-lib module for all of our new APIs anyway and we can convert over time.

**Comment by wshafer** [comment]
@rodmcnew - To answer your question, all we really need to do is tag the skeleton app.  All the plugins and modules use there own versioning, so they don't matter as much, because the 1.0 will be on the skeleton and it will map the other modules in it's composer package.

So after reading your guys comments here's what I see as the current roadmap for 1.0

* A completed theme with all the needed css for the "core" plugins
* Define a list of core plugins for this release
* Add Icons for "core" plugins
* Decouple the pages from the site entity
* Layout container must have a way to turn this off based on site.  (Sorry James, but outside of Reliv not being able to turn this off is a huge show stopper.)
* Document theme building and plugin writing.
* Move plugins out of rcm-plugin drawer
* Validate all the plugin modules have defined all their needed dependencies in their composer.json.
* Fix the login plugin to work outside of Reliv's Skeleton app.  (Currently the login plugin depends on code not released in OS)
* Clean up the installer
* Fix Rcm-Admin to work with the CMS route.  (PR coming soon)

Anything else we're missing?

**Comment by rodmcnew** [comment]
Sounds reasonable to me for what we need to do before 1.0.0 tag of skel app.

**Comment by rodmcnew** [comment]
Note about login plugin: I know there have recently been alot of PRs to clean reliv-specific code out of it. It may be completely clean now but i am not sure.

**Comment by jerv13** [comment]
RE: (Sorry James, but outside of Reliv not being able to turn this off is a huge show stopper.)

Was not my idea

**Comment by wshafer** [comment]
Ok...  Sounds like we're in agreement.  

@rodmcnew - Can you create two new mile-stones in the skeleton app for v1.0 and v2.0.  At that point I'll break out these issues into manageable user stories so we can keep track of what we've already agreed to and who is working on what and what is completed?

**Comment by rodmcnew** [comment]
Where did "decouple pages form site entity" come from?

**Comment by rodmcnew** [comment]
Also note: I wouldn't start any projects in the core repo right now. We may or may not be splitting into two parts, a framework independent, and a zf part. This is still being debated.

**Comment by wshafer** [comment]
@rodmcnew "Where did "decouple pages form site entity" come from?"  

That came from our earlier discussion on the site entity.  Some login pages are not in it so the login script has no where to go or redirect to after a login.

I'd also not if the PSR-7 and decoupling are scheduled for v 2.0...  perhaps its best if you create a 2.0 branch on those packages and put that work there?

**Comment by wshafer** [comment]
Or...  The other way.  Create a branch for 1.0 on those packages and we'll do our 1.0 work in it?

**Comment by rodmcnew** [comment]
Oh you just mean the special pages, not all pages. I see.

I think it will be at least a week or two before we decide what is happening with splitting the core so I don't know what to do with the branches yet. @jerv13 isn't here today and everything is up in the air. I think we need time before taking any action in the core.

We aren't ready to create any branching currently. Branching too soon is bad because any changes would have to be made in both places.

**Comment by rodmcnew** [comment]
To clear things up: even though PSR7 would be for 2.0, we may still want to split the core into two folders for 1.0. This split if it happened would not change the code, it would just organize two separate folders. Until Reliv makes a firm decision on supporting Symfony, we simply wont know what we are going to put time into. @jerv13

**Comment by wshafer** [comment]
Just be aware, that Symfony 3 is already in the works, should you decide to go that route.

**Comment by rodmcnew** [comment]
FYI for @wshafer  : It looks like we won't be splitting out the core anytime soon. We may wait till symfony 3 comes out and address symfony more then. You should be fine to PR against core for the RCM 1.0.0 release as much as you want for now.

**Comment by rodmcnew** [comment]
@wshafer FYI: Although we still completely agree with moving things toward PRS7, we have pretty much abandoned moving things toward Symfony any time soon if ever. I was the main person pushing this and now care less about it. Although Symfony has many small benefits compared to ZF, it really isn't different enough from ZF to go through the trouble of moving.

My personal take on things is like this: Our main MVC framework for new development is Angular, not ZF. When using Angular, the server's job is just REST services. Both ZF and SF are MVC frameworks themselves with REST functionality seemingly bolted on the side of the MVC. Making REST services is just as non-DRY and boilerplate-code-full in both ZF and SF. So, my personal interest for the server side is in finding the best ways to make REST services rather than pushing from ZF to SF.

Also: James is going to starting tagging 1.0 for RCM soon. (Today I think). @jerv13

**Comment by rodmcnew** [comment]
We tagged 1.0 so closing this
